import i18next from 'i18next';

export const SPEC_PREVIEW_ERRORS = {
  EMPTY: () => i18next.t('API_SPEC.PREVIEW_ERROR_EMPTY'),
  INVALID_YAML_JSON: () => i18next.t('API_SPEC.PREVIEW_ERROR_INVALID_YAML_JSON'),
  INVALID_OPENAPI: () => i18next.t('API_SPEC.PREVIEW_ERROR_INVALID_OPENAPI'),
  TIMEOUT: () => i18next.t('API_SPEC.PREVIEW_ERROR_TIMEOUT')
} as const;
